### ISSUE TITLE
This cancels "shoot", for example if you are using your wand.

### ISSUE THREAD

**Issue by jevring** [JamiePoole/TrackingSwitcher#1]

**Comment by JamiePoole** [comment]
Thanks! Will check it out and push up a fix.

**Comment by JamiePoole** [comment]
Okay weird, so it doesn't interrupt a Warrior's Shoot or a Hunter's Auto-Shoot, but I could replicate it on my Mage with Wand Shoot. Investigating :)

**Comment by JamiePoole** [comment]
Fixed. Pushing update.

**Comment by jevring** [comment]
It works now. Thanks for the quick fix =)
